# exportable session report: one self-contained HTML file (inline CSS + SVG, zero
# dependencies) built from db.get_session_report(). the jury/user can save it, mail it,
# open it offline -- it is the tangible artifact of a coding session

import html
import time

# server-side copy of frontend/src/theme.js STATE_COLORS -- test_session_report.py
# parses theme.js and asserts the two stay in sync
STATE_COLORS = {
    "DEEP_FOCUS": "#9B6AFF",
    "STRESSED": "#FF7A6A",
    "FATIGUED": "#FFB84A",
    "RELAXED": "#6AD89A",
    "WIRED": "#6AB8FF",
}

L = {
    "ro": {
        "title": "Raport de sesiune DevLife",
        "session": "Sesiunea", "duration": "Durata", "min": "min",
        "samples": "esantioane biometrice", "whoop": "WHOOP conectat",
        "yes": "da", "no": "nu (mock/BLE/tastare)",
        "states_title": "Timp petrecut pe stari cognitive",
        "hr_title": "Puls (bpm)", "hrv_title": "HRV (ms)",
        "min_lbl": "min", "max_lbl": "max", "avg_lbl": "mediu",
        "timeline_title": "Timeline puls, colorat pe stare",
        "interventions_title": "Interventiile ghost-ului",
        "no_interventions": "nicio interventie -- sesiune curata",
        "time": "ora", "state": "stare", "message": "mesaj",
        "footer": "generat de DevLife",
        "no_data": "sesiune fara date biometrice",
    },
    "en": {
        "title": "DevLife Session Report",
        "session": "Session", "duration": "Duration", "min": "min",
        "samples": "biometric samples", "whoop": "WHOOP connected",
        "yes": "yes", "no": "no (mock/BLE/typing)",
        "states_title": "Time per cognitive state",
        "hr_title": "Heart rate (bpm)", "hrv_title": "HRV (ms)",
        "min_lbl": "min", "max_lbl": "max", "avg_lbl": "avg",
        "timeline_title": "Heart-rate timeline, colored by state",
        "interventions_title": "Ghost interventions",
        "no_interventions": "no interventions -- clean session",
        "time": "time", "state": "state", "message": "message",
        "footer": "generated by DevLife",
        "no_data": "session without biometric data",
    },
}


def _fmt_time(ts):
    return time.strftime("%H:%M:%S", time.localtime(ts))


def _state_bars(shares, t):
    if not shares:
        return f'<p class="muted">{t["no_data"]}</p>'
    rows = []
    for state, share in sorted(shares.items(), key=lambda kv: -kv[1]):
        color = STATE_COLORS.get(state, "#888")
        pct = round(share * 100, 1)
        rows.append(
            f'<div class="bar-row"><span class="bar-label">{html.escape(state)}</span>'
            f'<div class="bar-track"><div class="bar" style="width:{pct}%;background:{color}"></div></div>'
            f'<span class="bar-pct">{pct}%</span></div>'
        )
    return "".join(rows)


def _timeline_svg(timeline, interventions, t):
    points = [(p["ts"], p["hr"], p["state"]) for p in timeline if p.get("hr")]
    if len(points) < 2:
        return f'<p class="muted">{t["no_data"]}</p>'
    w, h, pad = 720, 160, 24
    t0, t1 = points[0][0], points[-1][0]
    span = max(1.0, t1 - t0)
    hrs = [p[1] for p in points]
    lo, hi = min(hrs), max(hrs)
    rng = max(1.0, hi - lo)

    def x(ts):
        return pad + (ts - t0) / span * (w - 2 * pad)

    def y(hr):
        return h - pad - (hr - lo) / rng * (h - 2 * pad)

    segs = []
    for i in range(1, len(points)):
        a, b = points[i - 1], points[i]
        color = STATE_COLORS.get(b[2], "#888")
        segs.append(f'<line x1="{x(a[0]):.1f}" y1="{y(a[1]):.1f}" x2="{x(b[0]):.1f}" '
                    f'y2="{y(b[1]):.1f}" stroke="{color}" stroke-width="2"/>')
    ticks = []
    for iv in interventions:
        if t0 <= iv["ts"] <= t1:
            ticks.append(f'<line x1="{x(iv["ts"]):.1f}" y1="{pad}" x2="{x(iv["ts"]):.1f}" '
                         f'y2="{h - pad}" stroke="#FF7A6A" stroke-width="1" stroke-dasharray="3,3"/>')
    axis = (f'<text x="{pad}" y="{h - 6}" class="ax">{_fmt_time(t0)}</text>'
            f'<text x="{w - pad}" y="{h - 6}" class="ax" text-anchor="end">{_fmt_time(t1)}</text>'
            f'<text x="4" y="{y(hi):.0f}" class="ax">{hi:.0f}</text>'
            f'<text x="4" y="{y(lo):.0f}" class="ax">{lo:.0f}</text>')
    return (f'<svg viewBox="0 0 {w} {h}" role="img">'
            f'{"".join(segs)}{"".join(ticks)}{axis}</svg>')


def _interventions_table(interventions, t):
    if not interventions:
        return f'<p class="muted">{t["no_interventions"]}</p>'
    rows = "".join(
        f'<tr><td>{_fmt_time(iv["ts"])}</td>'
        f'<td><span class="dot" style="background:{STATE_COLORS.get(iv["state"], "#888")}"></span>{html.escape(iv["state"] or "")}</td>'
        f'<td>{html.escape((iv["claude_text"] or "")[:200])}</td></tr>'
        for iv in interventions
    )
    return (f'<table><thead><tr><th>{t["time"]}</th><th>{t["state"]}</th>'
            f'<th>{t["message"]}</th></tr></thead><tbody>{rows}</tbody></table>')


def _minmax(metric, t):
    if not metric:
        return '<p class="muted">--</p>'
    return (f'<p><strong>{metric["avg"]}</strong> {t["avg_lbl"]} · '
            f'{metric["min"]} {t["min_lbl"]} · {metric["max"]} {t["max_lbl"]}</p>')


def build_report_html(report, lang="ro"):
    t = L.get(lang, L["ro"])
    whoop = t["yes"] if report["whoop_connected"] else t["no"]
    return f"""<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8">
<title>{t["title"]} #{report["session_id"]}</title>
<style>
  body {{ font-family: -apple-system, 'Segoe UI', sans-serif; background: #16213e; color: #ffe4b5;
         max-width: 780px; margin: 24px auto; padding: 0 16px; }}
  h1 {{ font-size: 22px; }} h2 {{ font-size: 15px; margin-top: 28px; color: #B8A88C; }}
  .card {{ background: rgba(255,228,181,0.06); border-radius: 10px; padding: 14px 18px; margin: 10px 0; }}
  .muted {{ color: #8a7a5c; }}
  .meta {{ display: flex; gap: 24px; flex-wrap: wrap; font-size: 14px; }}
  .bar-row {{ display: flex; align-items: center; gap: 10px; margin: 6px 0; font-size: 13px; }}
  .bar-label {{ width: 110px; }} .bar-pct {{ width: 50px; text-align: right; }}
  .bar-track {{ flex: 1; background: rgba(255,228,181,0.08); border-radius: 4px; height: 14px; overflow: hidden; }}
  .bar {{ height: 100%; border-radius: 4px; }}
  svg {{ width: 100%; height: auto; background: rgba(0,0,0,0.25); border-radius: 8px; }}
  .ax {{ fill: #8a7a5c; font-size: 10px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th, td {{ text-align: left; padding: 6px 8px; border-bottom: 1px solid rgba(255,228,181,0.12); }}
  .dot {{ display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 6px; }}
  footer {{ margin: 30px 0 10px; font-size: 12px; color: #8a7a5c; }}
</style></head><body>
<h1>{t["title"]} <span class="muted">#{report["session_id"]}</span></h1>
<div class="card meta">
  <span>{t["duration"]}: <strong>{report["duration_min"]} {t["min"]}</strong></span>
  <span>{report["samples_count"]} {t["samples"]}</span>
  <span>{t["whoop"]}: {whoop}</span>
</div>
<h2>{t["states_title"]}</h2>
<div class="card">{_state_bars(report["state_shares"], t)}</div>
<h2>{t["hr_title"]} / {t["hrv_title"]}</h2>
<div class="card">
  {t["hr_title"]}: {_minmax(report["hr"], t)}
  {t["hrv_title"]}: {_minmax(report["hrv"], t)}
</div>
<h2>{t["timeline_title"]}</h2>
<div class="card">{_timeline_svg(report["timeline"], report["interventions"], t)}</div>
<h2>{t["interventions_title"]} ({len(report["interventions"])})</h2>
<div class="card">{_interventions_table(report["interventions"], t)}</div>
<footer>{t["footer"]} · {_fmt_time(report["started_at"])}</footer>
</body></html>"""
